pipeline {
    agent any
    tools { 
      maven 'Maven 3.8.7' 
      jdk 'jdk11' 
    }
    stages {
        stage('Build') { 
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
    }
}
